# Generated by Django 3.1 on 2020-09-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertravel',
            name='places',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
