# Generated by Django 3.1.2 on 2020-10-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_auto_20201004_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertravel',
            name='name',
        ),
        migrations.AlterField(
            model_name='usertravel',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
